name: paystack_flutter_sdk
description: "Paystack Flutter SDK with support for multiple channels to accept payments from your customers in supported regions."
version: 0.0.1-alpha.2
homepage: https://paystack.com
repository: https://github.com/PaystackOSS/paystack_flutter
issue_tracker: https://github.com/PaystackOSS/paystack_flutter/issues
documentation: https://paystack.com/docs
topics: [paystack, payments, cards, mpesa]


environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      android:
        package: com.paystack.paystack_sdk
        pluginClass: PaystackSDKPlugin
      ios:
        pluginClass: PaystackSDKPlugin